### ISSUE TITLE
 How can i get reconstruction picture

### ISSUE THREAD

**Issue by luocha0107** [NYCU-MAPL/Transformer_VariableROI#1]
hello,thank you for sharing.
can you tell me that how can i get reconstruction picture?

**Comment by NutsKing** [comment]
The pre-trained model weight is a bunch of data files. It's not a checkpoint. Looks like the author don't want to provide explanation or don't want you to use their trained model.

**Comment by luocha0107** [comment]
> The pre-trained model weight is a bunch of data files. It's not a checkpoint. Looks like the author don't want to provide explanation or don't want you to use their trained model.

all right. Thank you for reply !

**Comment by JoeK6279** [comment]
> hello,thank you for sharing. can you tell me that how can i get reconstruction picture?

Hello, sorry for the late reply. 
The model outputs a dict variable, the key "x_hat" refers to the reconstructed images.
You may call out_net ["x_hat"] to get the image in our [evaluation code](https://github.com/NYCU-MAPL/Transformer_VariableROI/blob/master/examples/eval_ROI.py#L218).

---

> The pre-trained model weight is a bunch of data files. It's not a checkpoint. Looks like the author don't want to provide explanation or don't want you to use their trained model.

Sorry for any confusion, but the released pre-trained weight is correct and a fairly common pytorch checkpoint file.
One may simply load it through our [evaluation code](https://github.com/NYCU-MAPL/Transformer_VariableROI/blob/master/examples/eval_variable.py#L272-L285).
If you have any further questions, please feel free to open a new issue.
